export const Route = {
  ButtonNavigator: 'buttonnavigator',
  Plans: 'plans',
  Qr: 'Qr',
  Maps: 'maps',
  profile: 'Profile',
  oauthscrean: 'oauthpage',
  OnBoard: 'onboardpage',
  Splash: 'splashpage',
  Home: 'homepage',
  Login: 'loginpage',
  Signup: 'signuppage',
  SignupInformation: 'signupinformationpage',
  OTP: 'otppage',
} as const;
